service: ecologi-sls-test

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    httpPort: 4000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: "yarn"

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
